// utils/quotes.ts
const quotes = [
  "“Success usually comes to those who are too busy to be looking for it.” – Henry David Thoreau",
  "“Choose a job you love, and you will never have to work a day in your life.” – Confucius",
  "“Opportunities don’t happen. You create them.” – Chris Grosser",
  "“Your résumé is not just a list of jobs, it's a story of who you are.”",
  "“If you need inspiration, don't do it.” – Elon Musk",
  "“The only way to do great work is to love what you do.” – Steve Jobs",
  // "“Measuring your résumé's ATS compatibility...”",
  "“Great résumés' tell stories, not just list experiences...”",
  "“Your experience is more valuable than you think.”",
  "“The only way to do great work is to love what you do.” – Steve Jobs",
  "“Analyzing your career journey for maximum impact...”",
  "“Fine-tuning your career highlights...”",
  "“Processing your professional DNA...”",
  "“AI is reading between the lines of your experience...”",
  "“Your career is a story, let’s make it compelling.”",
  "“Your résumé is your personal brand in action.”",
  "“Crafting a résumé is like writing a novel about your career.”",
  "“Decoding your career potential...”",
  "“Discovering the gems in your professional journey...",
  "“Almost there... crafting your feedback!”",
  "“Quality analysis takes a moment...”",
  "“Good things come to those who wait...”",
  "“Connecting the dots in your career...”",
  "“Generating personalized recommendations...”",
  "“Your professional audit is in progress...”",
  "“Letting the algorithms do the heavy lifting for you.”",
  "“Every great journey starts with a single step. You've taken it!”",
  "“Investing in your future. Good things take a moment.”",
  "“Sit tight, our digital expert is on the case!”",
  "“Scanning for awesomeness...”",
  "“Brewing up some great suggestions...”",
  "“Unveiling your résumé's superpowers...”",
  "“Hold tight, magic in progress!”",
  "“Hang tight! We’re giving your résumé the attention it deserves.”",
  "“Building the bridge to your next opportunity.”",
  "“The next chapter of your career is loading...”",
  "“Every career starts with a story. Let’s tell yours better.”",
  "“Your résumé is a reflection of your journey—let’s polish it to perfection.”",
];

export default quotes;
